# Generated by Django 4.2 on 2025-12-07 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about_url', models.URLField(unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_location', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes_scraper.author')),
                ('tags', models.ManyToManyField(blank=True, related_name='quotes', to='quotes_scraper.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['author'], name='quotes_scra_author__16c851_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('text', 'author')},
        ),
    ]
